# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [ push, pull_request, workflow_dispatch ]

env:
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        cache-dependency-path: src/main/webapp/package-lock.json

    - name: Adjust project version in pom.xml
      run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$(git describe --tags --always)

    - name: Build with Maven
      run: mvn -B verify --file pom.xml

    - name: Log in to Github Packages
      if: github.event_name != 'pull_request'
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      if: github.event_name != 'pull_request'
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/amurzeau/allocations-server

    - name: Build and push Docker image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: "./src/main/docker/Dockerfile.jvm"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Package quarkus-app to tar.gz
      run: tar -czf allocations-server.tar.gz -C target quarkus-app

    - uses: actions/upload-artifact@v2
      with:
        name: allocation-server
        path: allocations-server.tar.gz

    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: 'allocations-server.tar.gz'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
